

#define BYTE_CODE_STACK_MEMORY_ALLOCATE 0
#define BYTE_CODE_HEAP_MEMORY_ALLOCATE 1

#define BYTE_CODE_LOAD 2
#define BYTE_CODE_LOAD_GLOBAL 3

#define BYTE_CODE_CALL 4

#define BYTE_CODE_LOAD_IMPLICIT_VALUE 5

#define BYTE_CODE_POINTER_UP 6
#define BYTE_CODE_POINTER_DOWN 7


#define BYTE_CODE_END_CODE_BLOCK 8
