

#define AST_NODE_NAME_SPACE 0
#define AST_NODE_CODE_BLOCK 1
#define AST_NODE_VARIABLE_DECLARATION 2
#define AST_NODE_FUNCTION_DECLARATION 3
#define AST_NODE_STRUCT_DECLARATION 4
#define AST_NODE_EXPRESSION 5
#define AST_NODE_VALUE 6
#define AST_NODE_VARIABLE 7
#define AST_NODE_ASSIGNMENT 8
#define AST_NODE_FUNCTION_CALL 9
#define AST_NODE_POINTER_OPERATOR 10
#define AST_NODE_PARENTHESIS 11
#define AST_NODE_ACCESSING 12