

#define AST_NODE_NAME_SPACE 0
#define AST_NODE_CODE_BLOCK 1
#define AST_NODE_VARIABLE_DECLARATION 2
#define AST_NODE_FUNCTION_DECLARATION 3
#define AST_NODE_STRUCT_DECLARATION 4
#define AST_NODE_EXPRESSION 5
#define AST_NODE_VALUE 6
#define AST_NODE_VARIABLE 7
#define AST_NODE_ASSIGNMENT 8
#define AST_NODE_FUNCTION_CALL 9
#define AST_NODE_POINTER_OPERATION 10
#define AST_NODE_PARENTHESIS 11
#define AST_NODE_ACCESSING 12
#define AST_NODE_BYTE_CODE 13
#define AST_NODE_RETURN 14
#define AST_NODE_CAST 15



#define AST_DEBUG_MODE_INC 0
#define AST_DEBUG_MODE_DEC 1
#define AST_DEBUG_MODE_STL 2