

/* Primitives types size */

#define PRIMITIVE_TYPE_POINTER_SIZE 2
#define PRIMITIVE_TYPE_INT_SIZE 4
#define PRIMITIVE_TYPE_BYTE_SIZE 1
#define PRIMITIVE_TYPE_BOOL_SIZE 1
#define PRIMITIVE_TYPE_VOID_SIZE 0


/* Primitive Struct Name */

#define PRIMITIVE_TYPE_POINTER_NAME "Pointer"
#define PRIMITIVE_TYPE_INT_NAME "Int"
#define PRIMITIVE_TYPE_BYTE_NAME "Byte"
#define PRIMITIVE_TYPE_BOOL_NAME "Bool"
#define PRIMITIVE_TYPE_VOID_NAME "Void"

/* Function Name for operators */

#define FUNCTION_NAME_FUNCTION_OPERATOR_PLUS "add"
#define FUNCTION_NAME_FUNCTION_OPERATOR_MULTIPLICATION "mul"
#define FUNCTION_NAME_FUNCTION_OPERATOR_EQUAL "equal"
#define FUNCTION_NAME_FUNCTION_OPERATOR_PLUS_ASSIGN "add_assign"
