

/* Primitives types size */

#define PRIMITIVE_TYPE_POINTER_SIZE 2
#define PRIMITIVE_TYPE_INT_SIZE 4
#define PRIMITIVE_TYPE_BYTE_SIZE 1
#define PRIMITIVE_TYPE_BOOL_SIZE 1


/* Primitive Struct Name */

#define PRIMITIVE_TYPE_POINTER_NAME "Pointer"
#define PRIMITIVE_TYPE_INT_NAME "Int"
#define PRIMITIVE_TYPE_BYTE_NAME "Byte"
#define PRIMITIVE_TYPE_BOOL_NAME "Bool"

/* Function Name for operators */

#define FUNCTION_NAME_FUNCTION_OPERATOR_PLUS "add"
#define FUNCTION_NAME_FUNCTION_OPERATOR_NULTIPLICATION "mul"
